### ISSUE TITLE
trying to get slot "className" from an object (class "factor") that is not an S4 object 

### ISSUE THREAD

**Issue by mtaanman** [skardhamar/rga#1]
Hi, First of all thanks for the development.

My issue is that 3 days ago the package was working for me. Since 2 days ago I get an error when requesting data via ga$getData(). 

Expected output is a dataframe but what I get instead is an error in formatting:

Error in is(object, Class) : 
  trying to get slot "className" from an object (class "factor") that is not an S4 object 
In addition: Warning messages:
1: In `[<-.factor`(`*tmp*`, formats$dataType == "STRING", value = c(NA,  :
  invalid factor level, NAs generated
2: In `[<-.factor`(`*tmp*`, formats$dataType == "INTEGER", value = c(NA_integer_,  :
  invalid factor level, NAs generated
3: In `[<-.factor`(`*tmp*`, formats$dataType == "PERCENT", value = c(NA_integer_,  :
  invalid factor level, NAs generated
4: In `[<-.factor`(`*tmp*`, formats$dataType == "TIME", value = c(NA_integer_,  :
  invalid factor level, NAs generated
5: In `[<-.factor`(`*tmp*`, formats$dataType == "CURRENCY", value = c(NA_integer_,  :
  invalid factor level, NAs generated
6: In `[<-.factor`(`*tmp*`, formats$name == "date", value = c(NA_integer_,  :
  invalid factor level, NAs generated

I tried to solve it myself, but couldn't succeed. Any suggestions what might cause the problem here? My guess it is is the update google did on their API on the 14th. See: https://groups.google.com/forum/?fromgroups=#!topic/google-analytics-api-notify/j4crWq0bRb8. Thanks in advance!

Greetings, Menno

R version 2.15.2 (2012-10-26) -- "Trick or Treat"
Copyright (C) 2012 The R Foundation for Statistical Computing
ISBN 3-900051-07-0
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by hdk0310** [comment]
Hi ,
I am also facing similar kind of issue in my R code.
Error:  Exception in processPartitionForR: [trying to get slot "responses" from an object (class "randomForest.formula") that is not an S4 object ]
Can anyone help me on that
#code:
DT_pred_RF <- function(inp,n)
{
  #package DT random Forest
  library("randomForest")
  
  #Check whether value for the parameter predicted_rating_result_file_location has been provided
  if(!is.null(n[['predicted_rating_result_file_location']]))
    predicted_rating_result_file_location=n[['predicted_rating_result_file_location']]  else   stop("Parameter 

'predicted_rating_result_file_location' is null. Enter location where predicted ratings have to be saved.")
  
  #Check whether value for the parameter training_result_location has been provided
  if(!is.null(n[['training_result_location']])) training.result.file.location=n[['training_result_location']] else stop("Error: Please provide 

training result location")
  
  #Check whether training.result.file.location is a valid location
  if(!file.exists(dirname(training.result.file.location))) stop("Error: Invalid training location path")
  
  load(training.result.file.location)
  predicted.item.names <- c(DT$classes)
  #tr <- treeresponse(DT, newdata = inp)
  tr <- predict(DT, newdata = inp[,-1],OOB = TRUE, type='prob')
  res<-cbind(inp[,1],tr)
  write('3', file='~/vishal/pred_log',append=TRUE)
  colnames(res)<-c('msisdn',unlist(predicted.item.names))
  write('4', file='~/vishal/pred_log',append=TRUE)
  write.csv(res,
            predicted_rating_result_file_location,
            row.names =FALSE)
  return(data.frame(paste("Successfully generated predicted ratings. Results saved to '",predicted_rating_result_file_location,"'", sep="")))
}
DT_pred_RF_Factory <- function()
{
  list(name=DT_pred_RF,udxtype=c("transform"), intype=c("any"), outtype=c

("varchar"),parametertypecallback=DT_pred_RF_Parameters,outtypecallback=DT_pred_RF_ReturnType)
}
# call back function to return parameter types
DT_pred_RF_Parameters <- function()
{
  params <- data.frame(datatype=rep(NA, 1), length=rep(NA,1), scale=rep(NA,1), name=rep(NA,1) )
  params[1,1] = "varchar"
  params[1,4] = "predicted_rating_result_file_location"
  
  params[2,1] = "varchar"
  params[2,4] = "training_result_location"
  params
}


DT_pred_RF_ReturnType <- function(inp,n)
{
  ret <- data.frame(datatype=rep(NA, 1), length=rep(NA,1), scale=rep(NA,1),name=rep(NA,1) )
  #return information about training result after developing the model
  ret[1,1]=c("varchar")
  ret[1,2]=300
  ret[1,4]=c("Result")
  ret
  
}

--Thanks in Advance
