### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by ADRuf** [skardhamar/rga#100]
I'm getting this message when I try to access the Google Analytics API via R rga using the command: rga.open(instance = "ga")

Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In

This was working last month but now I keep getting this error. Any ideas?

**Comment by EricGoldsmith** [comment]
Doing a [Google Search](https://www.google.com/search?q=This+app+has+not+been+verified+yet+by+Google+in+order+to+use+Google+Sign+In&ie=UTF-8&oe=UTF-8&hl=en-us&client=safari) on that error message yields [this](https://support.google.com/cloud/answer/7454865) from Google. So, it seems to be specific to the credentials you're using. Perhaps that article will help you resolve it.

**Comment by ADRuf** [comment]
Thanks @EricGoldsmith. I saw that article but I couldn't figure out what to do next. I revised my programs to use googleAnalyticsR instead of rga and it is now working.

**Comment by EricGoldsmith** [comment]
FYI ... similar issue there: https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/292

**Comment by ADRuf** [comment]
Thanks! Looks like googleAnalyticsR was updated so it works as an alternative. Closing this issue.

**Comment by EricGoldsmith** [comment]
The change to `googleAnalyticsR` was to the default test account - no code changes to the package. IOW, the author followed the steps in the Google help article above to re-verify the test account.

Something similar for the default test account for this package could also be done, but would have to be done by @skardhamar, who owns the account.

That said, you shouldn't be using the default test account for anything other than testing, but should instead create your own account (as explained [here](https://github.com/skardhamar/rga#advanced-use)). Relying on the test account will subject you to the whims and abuse of anyone else using it.

**Comment by ADRuf** [comment]
Got it, I understand now. Thanks for your help and patience on this.

**Comment by MarkEdmondson1234** [comment]
Yes it was as @EricGoldsmith says, I needed to re-verify the app with updated scopes and a privacy policy links etc.  Long term its best to use your own OAuth2 app.
