### ISSUE TITLE
Problem installing package 

### ISSUE THREAD

**Issue by SJC1969** [skardhamar/rga#89]
I'm unable to install the package using:

    install.packages("skardhamar/rga") or install.packages("rga","skardhamar")

both result in the following:

    package is not available (for R version 3.3.2)

I'm new to this, so I might be doing something wrong.  Any assistance/guidance on what steps I should take would be greatly appreciated. 

Thanks in advance.

**Comment by EricGoldsmith** [comment]
The `rga` package is not available on CRAN, which is where `install.packages()` looks. Instead, you need to use `devtools::install_github()` from the `devtools` package.

**Comment by SJC1969** [comment]
Thanks, worked like a charm.  I hate being new to things.
