### ISSUE TITLE
And/or in filters

### ISSUE THREAD

**Issue by btoblerone** [skardhamar/rga#97]
Hi, 

I'm wondering how to apply multiple conditions to one filter in a query. 

Here's an example of one of my queries (which I know works):

customers_ab<-ga$getData(id, batch = TRUE, walk=TRUE, 
                          start.date = as.Date("2016-01-01"),
                          end.date = as.Date("2018-09-25"), 
                          metrics = "ga:totalEvents",
                          dimensions = "ga:day,ga:month,ga:year,ga:eventCategory,ga:pagePath",
                          filter = "ga:eventCategory=@Customers who viewed;ga:pagePath=@elisa")

What I would like to do is also be able to collect data for ga:pagePath=@immunoassay in the same query as the data for =@elisa. In the Google Analytics UI, I would just put in "elisa|immunoassay" into the advanced filter for Page. Is there a way to do this in rga without doing a separate query? I've tried playing with the code a few different ways but haven't been successful yet. 

Thank you!

**Comment by EricGoldsmith** [comment]
Hi there,

See the Filter Syntax section of this page:

https://developers.google.com/analytics/devguides/reporting/core/v3/reference

You can specify filters using regular expressions. So, in your example, you'd do:

```
filter = "ga:eventCategory=@Customers who viewed;ga:pagePath=~(elisa|immunoassay)"
```

**Comment by btoblerone** [comment]
@EricGoldsmith Thank you so much! I edited the code and the query ran perfectly. And thank you for that link! Bookmarked for the future :)
